// 节点配图注册表 · 图片在 public/media/，均来自 Wikimedia Commons（公有领域或 CC 授权）
// credit 注明作者与许可；由 grok-agent skill 的 download-commons.cjs 生成
window.CHEM_MEDIA = {
  "matter-change": { file: "media/matter-change.jpg", title: "铁锈与燃烧·化学变化示例", credit: "Vaikoovery · Wikimedia Commons · CC BY 3.0" },
  "pure-mixture": { file: "media/pure-mixture.jpg", title: "岩盐晶体·纯净物示例", credit: "David Monniaux (talk · contribs) · Wikimedia Commons · CC BY-SA 3.0" },
  "molecule-atom": { file: "media/molecule-atom.png", title: "水分子球棍模型", credit: "Dbc334 (first version); Jynto (second version) · Wikimedia Commons · Public domain" },
  "element": { file: "media/element.png", title: "元素单质样品陈列", credit: "2012rc · Wikimedia Commons · Public domain" },
  "atom-structure": { file: "media/atom-structure.png", title: "玻尔原子模型示意", credit: "JabberWok at English Wikipedia · Wikimedia Commons · CC BY-SA 3.0" },
  "ion": { file: "media/ion.png", title: "氯化钠离子晶体结构", credit: "H Padleckas · Wikimedia Commons · Public domain" },
  "formula-valence": { file: "media/formula-valence.png", title: "元素周期表·化合价参照", credit: "2012rc · Wikimedia Commons · Public domain" },
  "chemical-equation": { file: "media/chemical-equation.jpg", title: "拉瓦锡像·化学方程式奠基人", credit: "Louis Jean Désiré Delaistre (1800–1871); drawing by Julien L · Wikimedia Commons · Public domain" },
  "mass-conservation": { file: "media/mass-conservation.jpg", title: "拉瓦锡·质量守恒定律", credit: "Louis Jean Désiré Delaistre (1800–1871); drawing by Julien L · Wikimedia Commons · Public domain" },
  "oxidation-combustion": { file: "media/oxidation-combustion.jpg", title: "蜡烛燃烧·氧化反应", credit: "Vaikoovery · Wikimedia Commons · CC BY 3.0" },
  "air": { file: "media/air.png", title: "大气成分比例示意", credit: "Mysid · Wikimedia Commons · Public domain" },
  "oxygen": { file: "media/oxygen.jpg", title: "液氧·淡蓝色", credit: "U.S. Air Force photo/Staff Sgt. Nika Glover · Wikimedia Commons · Public domain" },
  "co2": { file: "media/co2.jpg", title: "干冰·固态二氧化碳", credit: "Uris at English Wikipedia · Wikimedia Commons · BSD" },
  "water": { file: "media/water.jpg", title: "水滴·水的组成与净化", credit: "Bobby9030 · Wikimedia Commons · CC BY-SA 4.0" },
  "carbon": { file: "media/carbon.jpg", title: "金刚石与石墨·碳的同素异形体", credit: "User:Itub · Wikimedia Commons · CC BY-SA 3.0" },
  "metals": { file: "media/metals.jpg", title: "天然铜·金属材料", credit: "Alchemist-hp (talk) (www.pse-mendelejew.de) · Wikimedia Commons · FAL" },
  "solution": { file: "media/solution.jpg", title: "硫酸铜溶液", credit: "Stephanb · Wikimedia Commons · CC BY-SA 3.0" },
  "acid": { file: "media/acid.jpg", title: "盐酸试剂瓶", credit: "Hari vinayak santhosh · Wikimedia Commons · CC BY-SA 4.0" },
  "base": { file: "media/base.jpg", title: "氢氧化钠固体", credit: "No machine-readable author provided. Walkerma assumed (based · Wikimedia Commons · Public domain" },
  "salt": { file: "media/salt.jpg", title: "岩盐晶体·盐类", credit: "Gendou · Wikimedia Commons · Public domain" },
  "neutralization": { file: "media/neutralization.jpg", title: "酸碱滴定·中和反应", credit: "Alina.Popova.26 · Wikimedia Commons · CC BY 4.0" },
  "ph": { file: "media/ph.png", title: "pH 标度与指示剂", credit: "Tristanevanslee · Wikimedia Commons · CC0" },
  "relative-atomic-mass": { file: "media/relative-atomic-mass.jpg", title: "道尔顿像·相对原子质量先驱", credit: "Charles Turner / After James Lonsdale · Wikimedia Commons · Public domain" },
  "relative-molecular-mass": { file: "media/relative-molecular-mass.jpg", title: "阿伏伽德罗像·分子质量概念", credit: "From a drawing by C. Sentier, executed in Torino at Litograf · Wikimedia Commons · Public domain" },
  "lab-basics": { file: "media/lab-basics.jpg", title: "化学实验室基本器具", credit: "Cjp24 · Wikimedia Commons · CC BY-SA 3.0" },
  "gas-prep": { file: "media/gas-prep.jpg", title: "启普发生器·气体发生装置", credit: "Carl Remigius Fresenius · Wikimedia Commons · Public domain" },
  "substance-id": { file: "media/substance-id.jpg", title: "焰色反应·物质鉴别", credit: "No machine-readable author provided. Burn~commonswiki assume · Wikimedia Commons · CC BY-SA 3.0" },
  "mole": { file: "media/mole.jpg", title: "阿伏伽德罗像·物质的量", credit: "From a drawing by C. Sentier, executed in Torino at Litograf · Wikimedia Commons · Public domain" },
  "material-classification": { file: "media/material-classification.jpg", title: "元素与化合物样品·物质分类", credit: "James St. John · Wikimedia Commons · CC BY 2.0" },
  "sodium": { file: "media/sodium.jpg", title: "金属钠单质", credit: "Greenhorn1 · Wikimedia Commons · Public domain" },
  "chlorine": { file: "media/chlorine.jpg", title: "氯气·黄绿色气体", credit: "Bowlhover 20:05, 21 January 2007 (UTC) · Wikimedia Commons · Public domain" },
  "iron": { file: "media/iron.jpg", title: "电解铁与铁立方", credit: "Alchemist-hp (talk) (www.pse-mendelejew.de) · Wikimedia Commons · FAL" },
  "sulfur-nitrogen": { file: "media/sulfur-nitrogen.jpg", title: "硫单质样品", credit: "Ben Mills · Wikimedia Commons · Public domain" },
  "periodic-law": { file: "media/periodic-law.jpg", title: "门捷列夫像·元素周期律", credit: "Ministry of Communications of the USSR. The design of the st · Wikimedia Commons · Public domain" },
  "chemical-bond": { file: "media/chemical-bond.png", title: "共价键与分子模型", credit: "Jacek FH · Wikimedia Commons · CC BY-SA 3.0" },
  "reaction-rate": { file: "media/reaction-rate.jpg", title: "镁条燃烧·反应速率示例", credit: "Capt. John Yossarian · Wikimedia Commons · CC BY-SA 3.0" },
  "organic-intro": { file: "media/organic-intro.png", title: "甲烷分子模型·有机入门", credit: "Wikimedia Commons · Public domain" },
  "ionization-eq": { file: "media/ionization-eq.jpg", title: "醋酸·弱电解质电离", credit: "Georg Biemann · Wikimedia Commons · CC BY-SA 3.0 de" },
  "salt-hydrolysis": { file: "media/salt-hydrolysis.png", title: "醋酸钠与 pH·盐类水解", credit: "Tristanevanslee · Wikimedia Commons · CC0" },
  "galvanic-cell": { file: "media/galvanic-cell.png", title: "原电池示意（丹尼尔电池）", credit: "Rehua · Wikimedia Commons · CC BY 3.0" },
  "electrolysis": { file: "media/electrolysis.jpg", title: "水的电解实验", credit: "Mattes · Wikimedia Commons · CC BY-SA 3.0" },
  "atom-property": { file: "media/atom-property.png", title: "原子半径趋势·原子性质", credit: "2012rc · Wikimedia Commons · Public domain" },
  "molecule-structure": { file: "media/molecule-structure.png", title: "甲烷分子立体结构", credit: "Wikimedia Commons · Public domain" },
  "crystal-structure": { file: "media/crystal-structure.png", title: "氯化钠晶体结构", credit: "H Padleckas · Wikimedia Commons · Public domain" },
  "hydrocarbon": { file: "media/hydrocarbon.png", title: "苯分子·芳香烃", credit: "Benjah-bmm27 · Wikimedia Commons · Public domain" },
  "organic-derivatives": { file: "media/organic-derivatives.png", title: "乙醇分子·烃的衍生物", credit: "Wikimedia Commons · Public domain" },
  "biomolecules": { file: "media/biomolecules.png", title: "DNA 结构·生物大分子", credit: "Zephyris · Wikimedia Commons · CC BY-SA 3.0" },
  "polymer": { file: "media/polymer.jpg", title: "聚乙烯颗粒·合成高分子", credit: "SuSanA Secretariat · Wikimedia Commons · CC BY 2.0" },
  "reaction-types": { file: "media/reaction-types.jpg", title: "碘化铅沉淀：化学反应的直观证据", credit: "LuisBrudna · Wikimedia Commons · CC BY-SA 4.0" },
  "formula-calc": { file: "media/formula-calc.png", title: "球棍分子模型：化学式的立体表达", credit: "Piswind · Wikimedia Commons · CC BY-SA 3.0" },
  "equation-calc": { file: "media/equation-calc.jpg", title: "分析天平：化学计算离不开称量", credit: "Делфина · Wikimedia Commons · CC BY-SA 4.0" },
  "salt-purification": { file: "media/salt-purification.jpg", title: "盐田蒸发结晶：粗盐提纯的天然版", credit: "Olga Ernst · Wikimedia Commons · CC BY-SA 4.0" },
  "reaction-energy": { file: "media/reaction-energy.jpg", title: "铝热反应：化学能的剧烈释放", credit: "User:Nikthestunned (Wikipedia) · Wikimedia Commons · CC BY-SA 3.0" },
  "metal-activity": { file: "media/metal-activity.jpg", title: "铁钉浸入硫酸铜：金属活动性", credit: "H. Hoffmeister · Wikimedia Commons · GFDL" },
  "solubility": { file: "media/solubility.jpg", title: "高锰酸钾溶解扩散", credit: "AnastasGatt · Wikimedia Commons · CC BY 4.0" },
  "solubility-eq": { file: "media/solubility-eq.jpg", title: "溶洞钟乳石：碳酸钙溶解平衡", credit: "Johnragla · Wikimedia Commons · CC0" },
  "mass-fraction": { file: "media/mass-fraction.jpg", title: "实验室配制溶液：质量分数", credit: "User:Ruhrfisch · Wikimedia Commons · CC BY-SA 3.0" },
  "ion-reaction": { file: "media/ion-reaction.jpg", title: "焰色反应：离子的指纹", credit: "Søren Wedel Nielsen · Wikimedia Commons · CC BY-SA 3.0" },
  "redox": { file: "media/redox.jpg", title: "金属锈蚀：氧化还原反应", credit: "Roger McLassus · Wikimedia Commons · CC BY-SA 3.0" },
  "reaction-heat": { file: "media/reaction-heat.jpg", title: "篝火燃烧：放热反应", credit: "Janne Karaste · Wikimedia Commons · CC BY-SA 3.0" },
  "equilibrium": { file: "media/equilibrium.png", title: "哈伯：合成氨与化学平衡的工业应用", credit: "The Nobel Foundation · Wikimedia Commons · Public domain" },
};
