// 初中化学知识体系 — 全骨架
// 用「依赖关系」组织，不分先后年级，只看知识依赖
// theme: matter（物质构成）| reaction（化学反应）| substances（常见物质）| quantitative（定量化学）| experiment（实验与方法）
// level: 在依赖图中的深度（用于星空自动布局和学习推荐）

window.CHEM_THEMES = {
  matter:       { name: '物质构成',   short: '构成', color: '#2563eb', soft: '#dbeafe', deep: '#1e40af' },
  reaction:     { name: '化学反应',   short: '反应', color: '#ea580c', soft: '#ffedd5', deep: '#9a3412' },
  substances:   { name: '常见物质',   short: '物质', color: '#16a34a', soft: '#dcfce7', deep: '#15803d' },
  quantitative: { name: '定量化学',   short: '定量', color: '#7c3aed', soft: '#ede9fe', deep: '#5b21b6' },
  experiment:   { name: '实验与方法', short: '实验', color: '#0d9488', soft: '#ccfbf1', deep: '#0f766e' },
  principle: { name: '反应原理', short: '原理', color: '#dc2626', soft: '#fee2e2', deep: '#991b1b' },
  organic:   { name: '有机化学', short: '有机', color: '#db2777', soft: '#fce7f3', deep: '#9d174e' },
};

// 节点：每个知识点
// {id, name, theme, level, prereqs[], concept, explanation, example, connections[]}
window.CHEM_NODES = [
  // ───── 物质构成 ─────
  { id:'matter-change', name:'物质的变化与性质', theme:'matter', level:1, prereqs:[],
    concept:'物理变化没有新物质生成，化学变化（化学反应）有新物质生成',
    explanation:'区分物理变化和化学变化是化学的第一道门：判断的唯一标准是「有没有生成新物质」。物理性质（颜色、状态、熔点）不需要发生化学变化就能表现，化学性质（可燃性、氧化性）必须通过化学变化才表现出来。',
    example:'水结冰、蜡熔化是物理变化；木炭燃烧、铁生锈是化学变化（生成了新物质）。',
    connections:['pure-mixture','molecule-atom','oxidation-combustion'] },
  { id:'pure-mixture', name:'纯净物与混合物', theme:'matter', level:2, prereqs:['matter-change'],
    concept:'纯净物只由一种物质组成；混合物由两种或多种物质混合而成',
    explanation:'纯净物有固定的组成和性质，可以用化学式表示；混合物没有固定组成，各成分保持各自性质。区分它们是研究空气、溶液、合金等的基础。',
    example:'蒸馏水是纯净物；空气、海水、合金都是混合物。',
    connections:['air','water','solution'] },
  { id:'molecule-atom', name:'分子和原子', theme:'matter', level:2, prereqs:['matter-change'],
    concept:'分子是保持物质化学性质的最小粒子；原子是化学变化中的最小粒子',
    explanation:'物质由微观粒子构成。化学变化中分子可以分成原子、原子再重新组合成新分子——而原子本身不变。这个微观图像是理解化学反应、质量守恒的根基。',
    example:'水分子由氢原子和氧原子构成；电解水时水分子分成氢、氧原子，重组为氢气和氧气分子。',
    connections:['element','atom-structure','mass-conservation'] },
  { id:'element', name:'元素', theme:'matter', level:3, prereqs:['molecule-atom'],
    concept:'具有相同核电荷数（质子数）的一类原子的总称',
    explanation:'元素是「种类」概念，只论种类不论个数。地壳中含量最多的元素是氧。元素周期表把已知元素按规律排列，是化学的「字典」。',
    example:'氢、氧、碳、铁都是元素；水（H₂O）由氢、氧两种元素组成。',
    connections:['formula-valence','metals','relative-atomic-mass'] },
  { id:'atom-structure', name:'原子结构', theme:'matter', level:3, prereqs:['molecule-atom'],
    concept:'原子由居于中心的原子核（质子+中子）和核外电子构成',
    explanation:'质子带正电、中子不带电、电子带负电。质子数 = 核外电子数，所以原子整体不显电性。核外电子分层排布，最外层电子数决定元素的化学性质。',
    example:'钠原子核内有 11 个质子，核外 11 个电子，最外层 1 个电子，容易失去，化学性质活泼。',
    connections:['ion','relative-atomic-mass'] },
  { id:'ion', name:'离子', theme:'matter', level:4, prereqs:['atom-structure'],
    concept:'原子得到或失去电子后形成的带电粒子',
    explanation:'原子失去电子带正电（阳离子），得到电子带负电（阴离子）。离子是构成物质的又一种基本粒子，氯化钠就由钠离子和氯离子构成。',
    example:'钠原子失去 1 个电子变成 Na⁺；氯原子得到 1 个电子变成 Cl⁻；两者结合成氯化钠。',
    connections:['formula-valence','acid','base'] },
  { id:'formula-valence', name:'化学式与化合价', theme:'matter', level:4, prereqs:['element','ion'],
    concept:'化学式用元素符号表示物质组成；化合价表示原子相互化合的数目关系',
    explanation:'化学式是物质的「身份证」，既表示物质又表示组成。化合价用来书写和检验化学式：化合物中正负化合价代数和为零。',
    example:'水的化学式 H₂O；钠为 +1 价、氯为 −1 价，所以氯化钠是 NaCl；钙 +2、氯 −1，氯化钙是 CaCl₂。',
    connections:['chemical-equation','relative-molecular-mass'] },

  // ───── 化学反应 ─────
  { id:'chemical-equation', name:'化学方程式', theme:'reaction', level:5, prereqs:['formula-valence'],
    concept:'用化学式表示化学反应的式子，遵守质量守恒，要配平',
    explanation:'化学方程式表示「反应物、生成物、条件」三件事，并通过配平体现质量守恒——等号两边每种原子的个数必须相等。它是定量研究化学反应的语言。',
    example:'碳燃烧：C + O₂ —点燃→ CO₂。两边碳、氧原子个数都相等，已配平。',
    connections:['reaction-types','equation-calc'] },
  { id:'mass-conservation', name:'质量守恒定律', theme:'reaction', level:5, prereqs:['molecule-atom'],
    concept:'参加化学反应的各物质质量总和，等于反应后生成的各物质质量总和',
    explanation:'微观上：化学反应前后原子的种类、数目、质量都不变，所以总质量守恒。它是配平化学方程式和一切化学计算的依据。',
    example:'铁在氧气中燃烧后质量增大，是因为结合了氧；若在密闭容器中称量，反应前后总质量不变。',
    connections:['chemical-equation','equation-calc'] },
  { id:'reaction-types', name:'基本反应类型', theme:'reaction', level:6, prereqs:['chemical-equation'],
    concept:'化合、分解、置换、复分解四种基本反应类型',
    explanation:'化合是「多变一」，分解是「一变多」，置换是单质与化合物反应生成另一单质和化合物，复分解是两种化合物互换成分。判断类型有助于预测产物。',
    example:'化合：C+O₂→CO₂；分解：2H₂O₂→2H₂O+O₂↑；置换：Fe+CuSO₄→FeSO₄+Cu；复分解：HCl+NaOH→NaCl+H₂O。',
    connections:['metal-activity','neutralization'] },
  { id:'oxidation-combustion', name:'氧化反应与燃烧', theme:'reaction', level:5, prereqs:['matter-change'],
    concept:'物质与氧发生的反应叫氧化反应；燃烧是剧烈的发光发热的氧化反应',
    explanation:'燃烧需要同时满足三个条件：可燃物、与氧气（或空气）接触、温度达到着火点。理解燃烧条件就能解释灭火原理（破坏任一条件即可）。',
    example:'木柴燃烧是剧烈氧化；铁生锈是缓慢氧化。灭火：用水降温、用锅盖隔绝空气、清除可燃物。',
    connections:['oxygen','carbon'] },

  // ───── 常见物质 ─────
  { id:'air', name:'空气', theme:'substances', level:3, prereqs:['pure-mixture'],
    concept:'空气是混合物，按体积约含氮气 78%、氧气 21%',
    explanation:'空气的成分是定量研究气体的起点。氧气支持燃烧和呼吸，氮气性质稳定常作保护气。测定空气中氧气含量的实验是经典探究。',
    example:'红磷在密闭装置中燃烧消耗氧气，水面上升约 1/5，说明氧气约占空气体积的 21%。',
    connections:['oxygen','co2'] },
  { id:'oxygen', name:'氧气', theme:'substances', level:4, prereqs:['air','oxidation-combustion'],
    concept:'无色无味的气体，化学性质比较活泼，支持燃烧和供给呼吸',
    explanation:'氧气是初中接触的第一种重点单质。它能与许多物质发生氧化反应。实验室常用过氧化氢或高锰酸钾分解制取，工业上分离液态空气获得。',
    example:'带火星的木条伸入氧气中复燃，可用来检验氧气；铁丝在氧气中剧烈燃烧、火星四射。',
    connections:['gas-prep','carbon'] },
  { id:'co2', name:'二氧化碳', theme:'substances', level:4, prereqs:['air'],
    concept:'无色无味的气体，密度比空气大，能溶于水，不支持燃烧',
    explanation:'二氧化碳与水反应生成碳酸，使紫色石蕊变红；与澄清石灰水反应变浑浊（检验方法）。它既是光合作用原料，也是主要温室气体。',
    example:'向澄清石灰水中通入 CO₂，石灰水变浑浊：CO₂+Ca(OH)₂→CaCO₃↓+H₂O，用来检验 CO₂。',
    connections:['gas-prep','substance-id'] },
  { id:'water', name:'水的组成与净化', theme:'substances', level:3, prereqs:['pure-mixture'],
    concept:'水由氢、氧两种元素组成；净化方法有沉淀、过滤、吸附、蒸馏',
    explanation:'电解水实验证明水由氢、氧元素组成（正氧负氢，体积比 1∶2）。净化按净化程度从低到高：沉淀→过滤→吸附→蒸馏，蒸馏得到的水最纯。',
    example:'电解水：2H₂O —通电→ 2H₂↑+O₂↑，负极氢气、正极氧气，体积比约 2∶1。',
    connections:['solution','salt-purification'] },
  { id:'carbon', name:'碳和碳的氧化物', theme:'substances', level:5, prereqs:['oxygen'],
    concept:'碳单质（金刚石、石墨、C₆₀）与一氧化碳、二氧化碳的性质',
    explanation:'同种元素可组成性质迥异的单质（金刚石硬、石墨软导电）——这是「结构决定性质」。碳充分燃烧生成 CO₂，不充分燃烧生成有毒的 CO。',
    example:'金刚石和石墨都由碳元素组成，但因原子排列不同，硬度和导电性差别巨大。',
    connections:['substance-id'] },
  { id:'metals', name:'金属与金属材料', theme:'substances', level:5, prereqs:['element'],
    concept:'金属的物理性质（导电导热、延展性、金属光泽）和合金',
    explanation:'金属大多有金属光泽、能导电导热、有延展性。合金是金属与其他元素熔合形成的混合物，性能往往优于纯金属（更硬、更耐腐蚀）。',
    example:'铁是用量最大的金属；生铁和钢都是铁合金；黄铜是铜锌合金，比纯铜更硬。',
    connections:['metal-activity'] },
  { id:'metal-activity', name:'金属活动性顺序', theme:'substances', level:6, prereqs:['metals','reaction-types'],
    concept:'金属按活动性由强到弱排列：K Ca Na Mg Al Zn Fe Sn Pb (H) Cu Hg Ag Pt Au',
    explanation:'活动性顺序用来判断金属能否与酸、与盐溶液反应：排在氢前的金属能置换出酸中的氢；排在前面的金属能把后面的金属从其盐溶液中置换出来。',
    example:'铁能与硫酸铜溶液反应：Fe+CuSO₄→FeSO₄+Cu（铁在铜前）；铜不能与稀盐酸反应（铜在氢后）。',
    connections:['substance-id'] },
  { id:'solution', name:'溶液', theme:'substances', level:4, prereqs:['water'],
    concept:'一种或几种物质分散到另一种物质里形成的均一、稳定的混合物',
    explanation:'溶液由溶质和溶剂组成（溶剂常为水）。溶液的基本特征是均一、稳定。理解溶液是学习溶解度、溶质质量分数和酸碱盐的前提。',
    example:'食盐水中食盐是溶质、水是溶剂；糖水、稀盐酸都是溶液。',
    connections:['solubility','mass-fraction','acid','base'] },
  { id:'acid', name:'酸', theme:'substances', level:6, prereqs:['solution','ion'],
    concept:'电离时生成的阳离子全部是氢离子（H⁺）的化合物',
    explanation:'酸有共同的化学性质，因为它们都能电离出 H⁺：能使紫色石蕊变红、与活泼金属反应放氢气、与碱中和、与某些盐反应。常见酸有盐酸、硫酸。',
    example:'稀盐酸与锌反应：Zn+2HCl→ZnCl₂+H₂↑；稀盐酸使紫色石蕊试液变红。',
    connections:['salt','neutralization','ph','substance-id'] },
  { id:'base', name:'碱', theme:'substances', level:6, prereqs:['solution','ion'],
    concept:'电离时生成的阴离子全部是氢氧根离子（OH⁻）的化合物',
    explanation:'碱也有共同性质，因为都能电离出 OH⁻：能使紫色石蕊变蓝、使无色酚酞变红、与酸中和、与某些盐反应。常见碱有氢氧化钠、氢氧化钙。',
    example:'氢氧化钠使无色酚酞变红；与盐酸中和：NaOH+HCl→NaCl+H₂O。',
    connections:['salt','neutralization','ph'] },
  { id:'salt', name:'盐', theme:'substances', level:7, prereqs:['acid','base'],
    concept:'由金属离子（或铵根）和酸根离子构成的化合物',
    explanation:'盐不一定是「咸的」——它是一大类化合物。盐能与酸、碱、其他盐以及金属发生复分解或置换反应，是物质鉴别和制备的核心。',
    example:'氯化钠、碳酸钙、硫酸铜都是盐；碳酸钙与盐酸反应：CaCO₃+2HCl→CaCl₂+H₂O+CO₂↑。',
    connections:['substance-id'] },
  { id:'neutralization', name:'中和反应', theme:'substances', level:7, prereqs:['acid','base'],
    concept:'酸与碱作用生成盐和水的反应',
    explanation:'中和反应的实质是 H⁺ 和 OH⁻ 结合生成水。它在生活中应用广泛：用熟石灰改良酸性土壤、用胃药中和过多胃酸。',
    example:'盐酸与氢氧化钠：HCl+NaOH→NaCl+H₂O。可借助酚酞由红变无色判断恰好中和。',
    connections:['ph'] },
  { id:'ph', name:'溶液酸碱度 pH', theme:'substances', level:7, prereqs:['acid','base'],
    concept:'用 pH 表示溶液的酸碱度，范围通常 0~14',
    explanation:'pH<7 显酸性，pH=7 中性，pH>7 显碱性，越偏离 7 酸碱性越强。用 pH 试纸或 pH 计测定，广泛用于农业、医疗和环境监测。',
    example:'胃液 pH 约 1~2（强酸性），纯水 pH=7，肥皂水 pH>7（碱性）。用 pH 试纸测定要与标准比色卡对照。',
    connections:['substance-id'] },

  // ───── 定量化学 ─────
  { id:'relative-atomic-mass', name:'相对原子质量', theme:'quantitative', level:4, prereqs:['atom-structure'],
    concept:'以碳-12 原子质量的 1/12 作标准，其他原子质量与之相比所得的比值',
    explanation:'原子真实质量极小，使用不便，于是用「相对」质量。相对原子质量没有单位（是比值），约等于质子数加中子数。它是一切化学计算的基础数据。',
    example:'氢的相对原子质量约为 1，氧约为 16，碳约为 12，铁约为 56。',
    connections:['relative-molecular-mass'] },
  { id:'relative-molecular-mass', name:'相对分子质量', theme:'quantitative', level:5, prereqs:['formula-valence','relative-atomic-mass'],
    concept:'化学式中各原子的相对原子质量的总和',
    explanation:'把化学式里每种原子的相对原子质量乘以个数再相加，就得到相对分子质量。它是计算元素质量分数、参与化学方程式计算的桥梁。',
    example:'水 H₂O：2×1+16=18；二氧化碳 CO₂：12+16×2=44。',
    connections:['formula-calc','equation-calc'] },
  { id:'formula-calc', name:'根据化学式计算', theme:'quantitative', level:6, prereqs:['relative-molecular-mass'],
    concept:'利用化学式计算相对分子质量、元素质量比和元素质量分数',
    explanation:'三类常见计算：相对分子质量、化合物中各元素的质量比、某元素的质量分数。它把化学式从「符号」变成可以算出含量的「数据」。',
    example:'水中氢、氧质量比 = (2×1)∶16 = 1∶8；氧的质量分数 = 16/18 ≈ 88.9%。',
    connections:[] },
  { id:'solubility', name:'溶解度', theme:'quantitative', level:5, prereqs:['solution'],
    concept:'一定温度下，某固态物质在 100 g 溶剂里达到饱和时所溶解的质量',
    explanation:'溶解度描述「溶解能力」，必须指明温度。多数固体溶解度随温度升高而增大。溶解度曲线用来分析结晶、升降温的影响。',
    example:'20°C 时氯化钠的溶解度约 36 g，表示 100 g 水最多溶解约 36 g 食盐达到饱和。',
    connections:['salt-purification'] },
  { id:'mass-fraction', name:'溶质质量分数', theme:'quantitative', level:6, prereqs:['solution'],
    concept:'溶质质量与溶液质量之比，常用百分数表示',
    explanation:'溶质质量分数 = 溶质质量 / 溶液质量 ×100%，其中溶液质量 = 溶质质量 + 溶剂质量。它是配制一定浓度溶液、稀释计算的核心。',
    example:'把 20 g 食盐溶于 80 g 水，溶质质量分数 = 20/(20+80) ×100% = 20%。',
    connections:[] },
  { id:'equation-calc', name:'根据化学方程式计算', theme:'quantitative', level:7, prereqs:['chemical-equation','relative-molecular-mass'],
    concept:'利用化学方程式中各物质的质量比进行定量计算',
    explanation:'配平后的化学方程式中，各物质的「相对分子质量×系数」之比就是它们的质量比。据此可由一种物质的质量求出另一种物质的质量，是初中化学计算的压轴。',
    example:'电解水 2H₂O→2H₂↑+O₂↑：H₂O 与 O₂ 的质量比 = (2×18)∶32 = 36∶32 = 9∶8。',
    connections:[] },

  // ───── 实验与方法 ─────
  { id:'lab-basics', name:'化学实验基本操作', theme:'experiment', level:1, prereqs:[],
    concept:'药品取用、加热、仪器使用与安全规范',
    explanation:'规范操作是化学实验安全和成功的前提：固体粉末用药匙、液体用量筒、加热用酒精灯外焰、闻气味要扇闻。错误操作可能造成危险或实验失败。',
    example:'取用液体时标签朝向手心、瓶塞倒放；给试管加热前要先预热，防止受热不均炸裂。',
    connections:['gas-prep','salt-purification'] },
  { id:'gas-prep', name:'常见气体的制取', theme:'experiment', level:5, prereqs:['oxygen','co2','lab-basics'],
    concept:'实验室制取氧气、二氧化碳的原理、装置与收集方法',
    explanation:'选择发生装置看反应条件（是否加热），选择收集方法看气体性质（密度、溶解性）。氧气可用排水法或向上排空气法，二氧化碳只能向上排空气法。',
    example:'制 O₂：2H₂O₂ —MnO₂→ 2H₂O+O₂↑；制 CO₂：CaCO₃+2HCl→CaCl₂+H₂O+CO₂↑。',
    connections:['substance-id'] },
  { id:'substance-id', name:'物质的检验与鉴别', theme:'experiment', level:6, prereqs:['acid','base','co2'],
    concept:'利用特征反应和现象区分、确认不同物质',
    explanation:'检验是「确认是不是它」，鉴别是「区分谁是谁」。要选择现象明显、互不干扰的特征反应：如用石灰水检验 CO₂，用石蕊/酚酞区分酸碱。',
    example:'区分稀盐酸和氢氧化钠溶液：滴入紫色石蕊，变红的是盐酸，变蓝的是氢氧化钠。',
    connections:[] },
  { id:'salt-purification', name:'粗盐提纯', theme:'experiment', level:5, prereqs:['solution','lab-basics'],
    concept:'通过溶解、过滤、蒸发把粗盐中的不溶性杂质除去',
    explanation:'粗盐提纯是综合实验：溶解（让食盐溶解、杂质不溶）、过滤（除去不溶物）、蒸发结晶（得到精盐）。过滤要「一贴二低三靠」，蒸发要用玻璃棒搅拌防飞溅。',
    example:'溶解粗盐→过滤除去泥沙→蒸发结晶得到较纯的氯化钠。过滤时漏斗下端紧靠烧杯内壁。',
    connections:[] },

  // ═════════════════ 高中部分 ═════════════════

  // ───── 高一 · 定量与分类 ─────
  { id:'mole', name:'物质的量', theme:'quantitative', level:7, prereqs:['relative-molecular-mass','formula-calc'],
    concept:'物质的量（单位摩尔，mol）是联系微观粒子数与宏观质量的桥梁，1 mol 含约 6.02×10²³ 个粒子',
    explanation:'初中只能数质量，高中要数「个数」。物质的量把阿伏伽德罗常数、摩尔质量、气体摩尔体积、物质的量浓度串成一张网。最易错的是把摩尔当成质量单位，以及谈「物质的量」却不指明是哪种粒子（原子？分子？离子？）。',
    example:'1 mol 水的质量等于其摩尔质量 $18\\,g/mol$，即 $18\\,g$；$n=\\dfrac{m}{M}=\\dfrac{N}{N_A}$。',
    connections:['ion-reaction','redox','equation-calc'] },
  { id:'material-classification', name:'物质的分类与转化', theme:'matter', level:3, prereqs:['matter-change','pure-mixture'],
    concept:'按组成把物质分为混合物与纯净物，纯净物再分单质、化合物（氧化物、酸、碱、盐），并研究它们之间的转化关系',
    explanation:'分类是高中化学的「地图」：知道一种物质属于哪一类，就能预测它大致有哪些性质和反应。常见陷阱是把「酸性氧化物」等同于「非金属氧化物」（如 Mn₂O₇ 是金属的酸性氧化物，CO 既不是酸性也不是碱性氧化物）。',
    example:'树状分类：物质→纯净物→化合物→氧化物→酸性氧化物（如 $CO_2$）；交叉分类：$Na_2CO_3$ 既是钠盐又是碳酸盐。',
    connections:['sodium','chlorine','iron'] },

  // ───── 高一 · 两大反应观 ─────
  { id:'ion-reaction', name:'离子反应', theme:'reaction', level:7, prereqs:['ion','solution','acid'],
    concept:'电解质在溶液中以离子形式参加的反应，用离子方程式表示',
    explanation:'初中写「分子方程式」，高中要看清溶液里真正反应的是哪些离子。书写离子方程式三大陷阱：强电解质拆、弱电解质和沉淀气体不拆；电荷要守恒；微溶物按状态决定拆不拆。复分解反应能发生的本质是生成沉淀、气体或水（自由离子浓度减小）。',
    example:'盐酸与氢氧化钠：$H^+ + OH^- = H_2O$；碳酸钙与盐酸：$CaCO_3 + 2H^+ = Ca^{2+} + H_2O + CO_2\\uparrow$。',
    connections:['salt-hydrolysis','ionization-eq','solubility-eq'] },
  { id:'redox', name:'氧化还原反应', theme:'reaction', level:7, prereqs:['reaction-types','oxidation-combustion'],
    concept:'有元素化合价升降（本质是电子转移）的反应，是贯穿高中化学的主线',
    explanation:'初中按「四种基本类型」分类，高中换一个更本质的视角：看化合价是否变化。升失氧（化合价升高、失电子、被氧化、是还原剂），降得还（化合价降低、得电子、被还原、是氧化剂）。这十二字口诀是配平、电化学、元素化合物的总钥匙。',
    example:'$2Na + Cl_2 = 2NaCl$ 中钠失电子（0→+1），氯得电子（0→−1）；电子转移用双线桥标注。',
    connections:['galvanic-cell','electrolysis','iron'] },

  // ───── 高一 · 元素化合物 ─────
  { id:'sodium', name:'钠及其化合物', theme:'substances', level:6, prereqs:['metals'],
    concept:'活泼金属钠及 Na₂O₂、NaOH、Na₂CO₃、NaHCO₃ 等钠的化合物的性质与转化',
    explanation:'钠是研究活泼金属的样板。要抓住「钠先与水反应而非置换出盐中金属」这一反常点，以及 Na₂CO₃ 与 NaHCO₃ 的鉴别与相互转化（俗称纯碱与小苏打）。Na₂O₂ 既作氧化剂又能供氧，是常考的反差点。',
    example:'$2Na + 2H_2O = 2NaOH + H_2\\uparrow$；$2Na_2O_2 + 2CO_2 = 2Na_2CO_3 + O_2$（潜水艇供氧）。',
    connections:['material-classification','chlorine','ion-reaction'] },
  { id:'chlorine', name:'氯及其化合物', theme:'substances', level:4, prereqs:['air'],
    concept:'氯气的强氧化性、与水和碱的反应，以及氯离子的检验',
    explanation:'氯气是典型的活泼非金属单质。难点是氯气与水反应生成 HCl 和 HClO（HClO 才有漂白、杀菌作用），以及「氯水」是混合体系（含多种分子和离子）。Cl⁻ 的检验用硝酸银和稀硝酸，要排除碳酸根等干扰。',
    example:'$Cl_2 + H_2O \\rightleftharpoons HCl + HClO$；检验氯离子：$Ag^+ + Cl^- = AgCl\\downarrow$（白色，不溶于稀硝酸）。',
    connections:['material-classification','sodium','redox'] },
  { id:'iron', name:'铁及其化合物', theme:'substances', level:7, prereqs:['metals','metal-activity'],
    concept:'铁及 Fe²⁺、Fe³⁺ 的性质、相互转化与检验',
    explanation:'铁有 +2 和 +3 两种常见价态，二者的相互转化是氧化还原的经典应用：Fe²⁺ 遇氧化剂升为 Fe³⁺，Fe³⁺ 遇还原剂（如铁粉）降为 Fe²⁺。检验 Fe³⁺ 用硫氰化钾（变血红色）。易错点是误以为铁与盐酸反应生成 Fe³⁺（实际生成 Fe²⁺）。',
    example:'$2Fe^{3+} + Fe = 3Fe^{2+}$；检验：$Fe^{3+}$ 遇 $KSCN$ 溶液变红，$Fe + 2HCl = FeCl_2 + H_2\\uparrow$。',
    connections:['material-classification','redox','galvanic-cell'] },
  { id:'sulfur-nitrogen', name:'硫、氮及其化合物', theme:'substances', level:5, prereqs:['air','co2'],
    concept:'SO₂、H₂SO₄、NH₃、HNO₃ 等含硫含氮化合物的性质及对环境的影响',
    explanation:'本节既讲性质（浓硫酸的吸水、脱水、强氧化性；浓硝酸的强氧化性；氨气的喷泉实验），又联系酸雨、光化学烟雾等环境问题，体现「化学与社会」。陷阱是浓、稀硫酸/硝酸性质差异大，以及 SO₂ 漂白（可逆、不能漂白指示剂）与氯水漂白机理不同。',
    example:'浓硫酸脱水：$C_{12}H_{22}O_{11}\\xrightarrow{浓H_2SO_4}12C+11H_2O$；铜与浓硝酸：$Cu+4HNO_3(浓)=Cu(NO_3)_2+2NO_2\\uparrow+2H_2O$。',
    connections:['material-classification','reaction-rate','ionization-eq'] },

  // ───── 高一 · 物质结构与周期律 ─────
  { id:'periodic-law', name:'原子结构与元素周期律', theme:'matter', level:4, prereqs:['atom-structure','element'],
    concept:'元素的性质随核电荷数递增呈周期性变化，集中体现在元素周期表中',
    explanation:'初中只认识周期表的「样子」，高中要懂它的「道理」：同周期从左到右原子半径减小、金属性减弱非金属性增强；同主族从上到下相反。「位—构—性」三者互推是核心方法。陷阱是把原子半径和离子半径、把金属性和金属活动性混为一谈。',
    example:'第三周期 $Na、Mg、Al$ 金属性依次减弱：$NaOH$ 强碱、$Mg(OH)_2$ 中强碱、$Al(OH)_3$ 两性。',
    connections:['chemical-bond','atom-property','sodium'] },
  { id:'chemical-bond', name:'化学键', theme:'matter', level:5, prereqs:['ion','molecule-atom'],
    concept:'相邻原子或离子间强烈的相互作用，分离子键和共价键',
    explanation:'化学键解释「原子为什么能结合成物质」：得失电子形成离子键，共用电子对形成共价键。判断陷阱：含金属或铵根 + 酸根多为离子化合物；只含非金属元素多为共价化合物（但 NH₄Cl 是含共价键的离子化合物）。化学反应的本质是旧键断裂、新键形成。',
    example:'$NaCl$ 含离子键；$HCl、H_2O$ 含共价键；$Na_2O_2$ 中既有离子键又有（过氧根内的）共价键。',
    connections:['molecule-structure','crystal-structure','reaction-energy'] },

  // ───── 高一 · 反应与能量 ─────
  { id:'reaction-energy', name:'化学反应与能量', theme:'reaction', level:6, prereqs:['chemical-equation','mass-conservation'],
    concept:'化学反应在生成新物质的同时伴随能量变化，分放热反应和吸热反应',
    explanation:'反应能量变化的本质是断键吸能、成键放能，二者的差额表现为放热或吸热。常见误区：把「需要加热才能进行」等同于「吸热反应」（如燃烧需点燃却放热），把物质状态、能量与化学能源应用割裂。这是后续焓变、原电池的基础。',
    example:'放热：$C+O_2\\xrightarrow{点燃}CO_2$（放热）；吸热：$C+CO_2\\xrightarrow{高温}2CO$。中和反应、金属与酸反应都放热。',
    connections:['reaction-rate','reaction-heat','chemical-bond'] },
  { id:'reaction-rate', name:'化学反应速率与限度', theme:'reaction', level:7, prereqs:['reaction-energy'],
    concept:'用单位时间内反应物或生成物浓度的变化量表示反应快慢；可逆反应有一定的限度',
    explanation:'影响速率的因素（浓度、温度、压强、催化剂）是定性规律，为高二的化学平衡铺路。难点是理解「可逆反应不能进行到底」，以及速率用任一物质表示时要除以化学计量数才能比较。注意固体、纯液体不影响速率（无浓度概念）。',
    example:'$2SO_2 + O_2 \\rightleftharpoons 2SO_3$ 是可逆反应；升温、加催化剂（如 $V_2O_5$）都能加快速率。',
    connections:['equilibrium','reaction-energy','sulfur-nitrogen'] },

  // ───── 高一 · 有机入门 ─────
  { id:'organic-intro', name:'有机化合物入门（甲烷·乙烯·乙醇·乙酸）', theme:'organic', level:6, prereqs:['carbon'],
    concept:'以甲烷、乙烯、乙醇、乙酸四种代表物初识有机化合物的组成、结构与典型反应',
    explanation:'从初中的碳单质过渡到「含碳化合物」的大家族。四种代表物分别对应烷烃（取代反应）、烯烃（加成反应）、醇、羧酸（酯化反应），先建立「官能团决定性质」的核心观念，为系统学习烃和衍生物打基础。',
    example:'甲烷取代：$CH_4 + Cl_2 \\xrightarrow{光照} CH_3Cl + HCl$；乙醇与乙酸酯化生成乙酸乙酯（有香味）。',
    connections:['hydrocarbon','organic-derivatives'] },

  // ───── 高二 · 反应原理 ─────
  { id:'reaction-heat', name:'反应热与焓变', theme:'principle', level:7, prereqs:['reaction-energy'],
    concept:'恒压条件下反应吸收或放出的热量叫反应热，用焓变 ΔH 定量描述',
    explanation:'把高一的「放热/吸热」定量化：放热 ΔH<0，吸热 ΔH>0。热化学方程式必须标明状态和 ΔH，且系数加倍则 ΔH 加倍。盖斯定律（反应热只与始末状态有关）是计算难以直接测定反应热的利器。最大陷阱是丢正负号、漏聚集状态。',
    example:'$H_2(g)+\\dfrac{1}{2}O_2(g)=H_2O(l)\\quad \\Delta H=-285.8\\,kJ/mol$（负号表示放热）。',
    connections:['equilibrium','galvanic-cell'] },
  { id:'equilibrium', name:'化学平衡', theme:'principle', level:8, prereqs:['reaction-rate'],
    concept:'可逆反应中正逆反应速率相等、各组分浓度不再变化的状态；条件改变时平衡会移动',
    explanation:'平衡是「动态」的（正逆速率相等而非反应停止）。勒夏特列原理：改变一个条件，平衡向减弱这种改变的方向移动。难点是用平衡常数 K 判断方向和转化率，以及区分「速率变化」与「平衡移动」（如加催化剂只变速率不移平衡）。',
    example:'合成氨 $N_2+3H_2\\rightleftharpoons 2NH_3$：增大压强平衡正向移动；升温平衡逆向移动（正反应放热）。',
    connections:['ionization-eq','salt-hydrolysis','solubility-eq'] },
  { id:'ionization-eq', name:'弱电解质的电离平衡', theme:'principle', level:7, prereqs:['acid','base'],
    concept:'弱电解质在水中部分电离，电离过程是可逆的，存在电离平衡',
    explanation:'初中默认酸碱「完全」反应，高中区分强、弱电解质：强酸强碱完全电离，弱酸弱碱（如醋酸、氨水）只部分电离，存在平衡。这是理解 pH、水解、缓冲的前提。陷阱是把「弱」等同于「稀」、把电离程度与溶液导电能力简单挂钩。',
    example:'醋酸电离：$CH_3COOH \\rightleftharpoons CH_3COO^- + H^+$；加水稀释促进电离，但 $H^+$ 浓度反而减小。',
    connections:['salt-hydrolysis','equilibrium','sulfur-nitrogen'] },
  { id:'salt-hydrolysis', name:'盐类的水解', theme:'principle', level:8, prereqs:['salt','ionization-eq'],
    concept:'盐电离出的离子与水电离出的 H⁺ 或 OH⁻ 结合，促进水的电离，使溶液显酸性或碱性',
    explanation:'解释了「为什么盐溶液不一定中性」这一初中遗留疑问。规律是「有弱才水解、谁强显谁性」：强碱弱酸盐显碱性，强酸弱碱盐显酸性。难点是水解程度一般很小、双水解可彻底进行，以及水解与电离对溶液酸碱性的竞争。',
    example:'碳酸钠水解显碱性：$CO_3^{2-}+H_2O \\rightleftharpoons HCO_3^-+OH^-$；氯化铵溶液显酸性。',
    connections:['ion-reaction','ionization-eq','equilibrium'] },
  { id:'solubility-eq', name:'沉淀溶解平衡', theme:'principle', level:6, prereqs:['solubility'],
    concept:'难溶电解质在溶液中存在溶解与沉淀的动态平衡，用溶度积 Ksp 描述',
    explanation:'把初中的「难溶」定量化：没有绝对不溶，只有溶解度大小。用 Ksp 比较溶解能力、判断沉淀的生成与溶解、实现沉淀的转化（向 Ksp 更小的方向转化）。陷阱是只有相同类型的难溶物才能直接用 Ksp 比较溶解度。',
    example:'$AgCl \\rightleftharpoons Ag^+ + Cl^-$，$K_{sp}=c(Ag^+)\\cdot c(Cl^-)$；加入 $Na_2S$ 可使 $AgCl$ 转化为更难溶的 $Ag_2S$。',
    connections:['ion-reaction','equilibrium'] },
  { id:'galvanic-cell', name:'原电池', theme:'principle', level:8, prereqs:['redox'],
    concept:'把化学能直接转化为电能的装置，本质是自发的氧化还原反应',
    explanation:'原电池是氧化还原反应的「空间分离」：负极失电子（被氧化），正极得电子（被还原），电子经外电路定向移动形成电流。判断电极、写电极反应式是核心，难点在盐桥的作用和电极反应式相加要等于总反应。',
    example:'铜锌原电池（稀硫酸）：负极 $Zn-2e^-=Zn^{2+}$，正极 $2H^++2e^-=H_2\\uparrow$。',
    connections:['electrolysis','redox','reaction-heat'] },
  { id:'electrolysis', name:'电解池与电解原理', theme:'principle', level:9, prereqs:['galvanic-cell'],
    concept:'把电能转化为化学能的装置，使不能自发进行的氧化还原反应得以发生',
    explanation:'与原电池相反：阳极（接电源正极）失电子发生氧化，阴极（接电源负极）得电子发生还原。难点是惰性电极与活性电极、离子的放电顺序，以及电解、电镀、电解精炼的应用。注意阴阳极的判断依据是外接电源而非反应类型本身。',
    example:'电解饱和食盐水（氯碱工业）：阳极 $2Cl^--2e^-=Cl_2\\uparrow$，阴极 $2H_2O+2e^-=H_2\\uparrow+2OH^-$。',
    connections:['galvanic-cell','redox'] },

  // ───── 高二 · 物质结构（选择性必修）─────
  { id:'atom-property', name:'原子结构与性质', theme:'matter', level:5, prereqs:['periodic-law'],
    concept:'用核外电子排布（能级、能层、电子云）深入解释原子结构与元素性质的周期性',
    explanation:'把高一的周期律「升级」到电子排布层面：用构造原理写电子排布式，用电离能、电负性定量比较金属性非金属性。难点是排布式的特例（如 Cr、Cu 的半充满、全充满）和电离能的反常变化。',
    example:'基态铁原子电子排布式 $1s^2\\,2s^2\\,2p^6\\,3s^2\\,3p^6\\,3d^6\\,4s^2$；电负性 $F>O>N$。',
    connections:['molecule-structure','crystal-structure'] },
  { id:'molecule-structure', name:'分子结构与性质', theme:'matter', level:6, prereqs:['chemical-bond'],
    concept:'用共价键参数、杂化轨道和价层电子对互斥理论解释分子的空间构型与性质',
    explanation:'回答「分子为什么是这个形状」：用 VSEPR 和杂化理论预测构型（直线、三角形、四面体等），用极性、氢键解释熔沸点和溶解性差异。难点是判断分子极性（构型对称则非极性）和氢键对物理性质的影响。',
    example:'$CO_2$ 直线形（非极性），$H_2O$ 为 $sp^3$ 杂化、V 形（极性）；水因氢键沸点反常偏高。',
    connections:['crystal-structure','organic-derivatives'] },
  { id:'crystal-structure', name:'晶体结构与性质', theme:'matter', level:6, prereqs:['chemical-bond'],
    concept:'按微粒和作用力把晶体分为分子晶体、原子（共价）晶体、金属晶体、离子晶体',
    explanation:'用「构成微粒 + 微粒间作用力」解释物质宏观性质（硬度、熔沸点、导电性）的差异，把高一「结构决定性质」推向晶体层面。难点是熔沸点高低比较（一般原子晶体>离子晶体>分子晶体）和均摊法计算晶胞中的微粒数。',
    example:'金刚石是原子晶体（熔点极高），干冰（$CO_2$）是分子晶体（易升华），$NaCl$ 是离子晶体。',
    connections:['molecule-structure','atom-property'] },

  // ───── 高二 · 有机化学（选择性必修）─────
  { id:'hydrocarbon', name:'烃（烷烯炔与芳香烃）', theme:'organic', level:7, prereqs:['organic-intro'],
    concept:'只含碳、氢两种元素的有机物，按碳骨架与饱和程度分为烷烃、烯烃、炔烃和芳香烃',
    explanation:'系统化高一的有机入门：烷烃稳定易取代、烯烃炔烃含不饱和键易加成与聚合、苯环结构特殊（不是单双键交替）。难点是同分异构体的书写和命名，以及不同类烃的鉴别（如用溴水区分烷烃与烯烃）。',
    example:'乙烯加成：$CH_2=CH_2 + Br_2 \\rightarrow CH_2BrCH_2Br$（溴水褪色，可鉴别）；苯不能使溴水因加成而褪色。',
    connections:['organic-derivatives','organic-intro'] },
  { id:'organic-derivatives', name:'烃的衍生物', theme:'organic', level:8, prereqs:['hydrocarbon'],
    concept:'烃分子中的氢被官能团取代后形成的化合物，如卤代烃、醇、醛、羧酸、酯',
    explanation:'核心是「官能团决定性质」：羟基（醇）、醛基、羧基、酯基各有特征反应，并能通过氧化、酯化、水解相互转化，构成有机推断的「转化网络」。难点是官能团的相互转化关系和有机合成路线的设计。',
    example:'乙醇氧化为乙醛再为乙酸：$2CH_3CH_2OH+O_2\\xrightarrow{Cu,\\Delta}2CH_3CHO+2H_2O$；酯化：$CH_3COOH+C_2H_5OH\\rightleftharpoons CH_3COOC_2H_5+H_2O$。',
    connections:['biomolecules','polymer','molecule-structure'] },

  // ───── 高三 · 有机大分子 ─────
  { id:'biomolecules', name:'生物大分子（糖类·蛋白质·油脂）', theme:'organic', level:9, prereqs:['organic-derivatives'],
    concept:'糖类、油脂、蛋白质等与生命活动密切相关的天然有机大分子的组成与性质',
    explanation:'把有机官能团知识应用到生命物质：糖类是多羟基醛/酮、蛋白质由氨基酸缩合而成、油脂是高级脂肪酸甘油酯。难点是各类物质的水解产物和特征检验（如葡萄糖的银镜反应、蛋白质的颜色反应与变性）。',
    example:'葡萄糖银镜反应可检验醛基；蛋白质遇浓硝酸变黄（颜色反应）；油脂在碱性条件下水解（皂化反应）制肥皂。',
    connections:['polymer','organic-derivatives'] },
  { id:'polymer', name:'合成高分子材料', theme:'organic', level:9, prereqs:['organic-derivatives'],
    concept:'由小分子单体通过加聚或缩聚反应连接成的高分子化合物，如塑料、合成纤维、合成橡胶',
    explanation:'把有机反应推向材料应用：加聚反应（不饱和键打开相连，无小分子生成）和缩聚反应（脱去水等小分子）是两条主线。难点是由单体推聚合物（或反推）、判断聚合类型，并联系白色污染、可降解材料等社会议题。',
    example:'乙烯加聚成聚乙烯：$nCH_2=CH_2 \\xrightarrow{催化剂} \\ce{[CH_2-CH_2]_n}$（塑料的主要成分之一）。',
    connections:['biomolecules','organic-derivatives'] },
];

// 推导：边集合（由 prereqs 自动生成）
window.CHEM_EDGES = window.CHEM_NODES.flatMap(n =>
  (n.prereqs || []).map(p => ({ from: p, to: n.id }))
);

// 节点查询
window.CHEM_NODE_BY_ID = Object.fromEntries(window.CHEM_NODES.map(n => [n.id, n]));

// 每条边的「教学理由」——为什么先学 A 才能学 B（自动生成中性表述）
function edgeReason(fromId, toId) {
  const from = window.CHEM_NODE_BY_ID[fromId];
  const to = window.CHEM_NODE_BY_ID[toId];
  if (!from || !to) return '';
  const cross = from.theme === to.theme ? '' : '跨主题地';
  return `${from.name}提供了${to.name}所需的概念、符号或实验基础，先理解它，才能${cross}把${to.name}里的物质、反应和计算说清楚。`;
}

window.CHEM_EDGE_WHY = Object.fromEntries(
  window.CHEM_EDGES.map(e => [`${e.from}→${e.to}`, edgeReason(e.from, e.to)])
);

// 年级标注（人教版：初中化学集中在九年级，分九年级上 / 九年级下）；用于详情页标签与新手引导筛选
window.CHEM_NODE_GRADE = {
  // 九年级上：物质构成、空气氧气、水、化学方程式、碳、燃烧、质量守恒、实验基础、定量基础
  'matter-change':'九年级上','pure-mixture':'九年级上','molecule-atom':'九年级上','element':'九年级上','atom-structure':'九年级上','ion':'九年级上','formula-valence':'九年级上',
  'chemical-equation':'九年级上','mass-conservation':'九年级上','oxidation-combustion':'九年级上',
  'air':'九年级上','oxygen':'九年级上','co2':'九年级上','water':'九年级上','carbon':'九年级上',
  'relative-atomic-mass':'九年级上','relative-molecular-mass':'九年级上','formula-calc':'九年级上',
  'lab-basics':'九年级上','gas-prep':'九年级上',
  // 九年级下：金属、溶液、酸碱盐、pH、相关计算与鉴别
  'reaction-types':'九年级下','metals':'九年级下','metal-activity':'九年级下','solution':'九年级下',
  'acid':'九年级下','base':'九年级下','salt':'九年级下','neutralization':'九年级下','ph':'九年级下',
  'solubility':'九年级下','mass-fraction':'九年级下','equation-calc':'九年级下',
  'substance-id':'九年级下','salt-purification':'九年级下',
  // 高一：物质的量、分类、离子反应、氧化还原、元素化合物、周期律、化学键、反应与能量、有机入门
  'mole':'高一','material-classification':'高一','ion-reaction':'高一','redox':'高一',
  'sodium':'高一','chlorine':'高一','iron':'高一','sulfur-nitrogen':'高一',
  'periodic-law':'高一','chemical-bond':'高一','reaction-energy':'高一','reaction-rate':'高一','organic-intro':'高一',
  // 高二：反应原理（焓变、平衡、电离、水解、沉淀溶解、电化学）、物质结构、烃与衍生物
  'reaction-heat':'高二','equilibrium':'高二','ionization-eq':'高二','salt-hydrolysis':'高二','solubility-eq':'高二',
  'galvanic-cell':'高二','electrolysis':'高二','atom-property':'高二','molecule-structure':'高二','crystal-structure':'高二',
  'hydrocarbon':'高二','organic-derivatives':'高二',
  // 高三：生物大分子、合成高分子
  'biomolecules':'高三','polymer':'高三',
};
window.CHEM_GRADE_RANK = { '九年级上':1, '九年级下':2, '高一':4, '高二':5, '高三':6 };
